server:
  port: 8080

spring:
  application:
    name: mqtt-im

  data:
    redis:
      database: 13
      host: 172.72.16.190
      port: 6379
      password: Puppet17.
      timeout: 3000

minio:
  endpoint: http://117.72.16.190:9000
  access-key: gak237I5taEdwW9Mzj8l
  secret-key: 9XTQ9wYwy3MA4QPcZJC55ruqV2D6EkjOl0cZYr3q
  bucket:
    name: mqtt

logging:
  level:
    root: INFO
